### ISSUE TITLE
Left 4 Bots 2 temporary heal command

### ISSUE THREAD

**Issue by RB490** [smilz0/Left4Bots#34]
**Describe the bug**
Version 1 has a 'bot tempheal' command in addition to just 'heal'. I have looked and can't find a similar option in version 2

**To Reproduce**
'bot tempheal'
scripted_user_func l4b,bots,tempheal

**Expected behavior**
Bot uses a temporary heal item

**Comment by smilz0** [comment]
The L4B1 features are slowly being reimplemented. The 'tempheal' command is already in the version you can find in the 'out' folder of this repository. Or you can wait the next update on the workshop.

**Comment by RB490** [comment]
Much appreciated! Love the mod
