### ISSUE TITLE
Automation system

### ISSUE THREAD

**Issue by smilz0** [smilz0/Left4Bots#72]
New automation system that executes a script file for each map. The script file defines the actions (tasks) that the bots must take in order to complete the map, like pressing buttons, open doors, scavenge etc. This will allow the bots to complete the campaign autonomously.
The systen will load the first .nut file it will find from the `scripts/vscripts/left4bots2/automation` folder in this order:
```
1. scripts/vscripts/left4bots2/automation/[base mode name]/[map name].nut
2. scripts/vscripts/left4bots2/automation/[base mode name]/l4b_[map name].nut
3. scripts/vscripts/left4bots2/automation/[base mode name]/automation_map_default.nut
4. scripts/vscripts/left4bots2/automation/[base mode name]/l4b_automation_map_default.nut
```
L4B2 will implement the `scripts/vscripts/left4bots2/automation/coop/l4b_[map name].nut` version for all the official campaign as well as the `l4b_automation_map_default.nut` one for maps without a script. The users will be able to override them with their own `scripts/vscripts/left4bots2/automation/coop/[map name].nut` and `automation_map_default.nut` versions.
Custom map makers can either include the `l4b_[map name].nut` to let the users make their own version or directly the `[map name].nut` into their map's .vpk.

**Comment by BTFighter** [comment]
Is 5+ survivors support planned? The system ignores the other 4 survivors when having 8 survivors.
