### ISSUE TITLE
When swapping your weapon with the bot, you'll find that it has no ammo.

### ISSUE THREAD

**Issue by NewbieZz** [smilz0/Left4Bots#86]
When swapping your weapon with the bot, you'll find that it has no ammo.

**Comment by 4512369781** [comment]
@smilz0 
I fix it, finally...
[fix_swap_no_ammo.zip](https://github.com/smilz0/Left4Bots/files/14669714/fix_swap_no_ammo.zip)

**Comment by NewbieZz** [comment]
Wow it's working, good job

> @smilz0 I fix it, finally... [fix_swap_no_ammo.zip](https://github.com/smilz0/Left4Bots/files/14669714/fix_swap_no_ammo.zip)

**Comment by 4512369781** [comment]
@NewbieZz
Hi, new update has released, don't forget delete the "left4bots_afterload.nut" file.
